#!/usr/bin/env python3
#
# MIT License
#
# (C) Copyright 2025 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# This file is read and used when generating cloud-init user-data, any repository and package listed here will be
# added to an NCN during cloud-init.
---
# All repos need to use a URL that is available during the PIT and after the PIT is gone, but resolves to the correct
# nexus in either context.
# The `packages` URL resolves to the PIT nexus and the Kubernetes nexus when in a bootstrap
# and runtime environment (respectively).
zypper:
  repos:
    - id: csm-noos
      name: csm-noos
      baseurl: "https://packages.local/repository/csm-noos?ssl_verify=no"
      enabled: 1
      autorefresh: 1
      gpgcheck: 1
      repo_gpgcheck: 0
    # Use Zypper friendly variables so the correct service pack repository is added.
    # NEVER force add a distro repository, or packages that do care about the distro version can break.
    - id: csm-sle
      name: "csm-sle-${releasever_major}sp${releasever_minor}"
      baseurl: "https://packages.local/repository/csm-sle-${releasever_major}sp${releasever_minor}?ssl_verify=no"
      enabled: 1
      autorefresh: 1
      gpgcheck: 1
      repo_gpgcheck: 0
# List of packages to install. These do not need version pins, because the latest version in nexus is determined by this
# tarball. Version pinning here would be redundant, and likely lead to more failures if anyone neglected updating it.
packages:
  - cani
  - canu
  - cray-cmstools-crayctldeploy
  - cray-site-init
  - craycli
  - csm-testing
  - goss-servers
  - hpe-csm-goss-package
  - iuf-cli
  - libcsm
  - platform-utils
