#
# MIT License
#
# (C) Copyright 2024 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
apiVersion: manifests/v1beta1
metadata:
  name: platform
spec:
  sources:
    charts:
    - name: csm-algol60
      type: repo
      location: https://artifactory.algol60.net/artifactory/csm-helm-charts/
  charts:
  - name: cray-drydock
    source: csm-algol60
    version: 2.18.4
    namespace: loftsman
    values:
      kubectl:
        image:
          repository: registry.local/artifactory.algol60.net/csm-docker/stable/docker-kubectl
          tag: 1.24.17
      sonar:
        jobsWatcher:
          image:
            repository: registry.local/artifactory.algol60.net/csm-docker/stable/cray-sonar
  - name: cray-kyverno
    source: csm-algol60
    version: 1.6.5
    namespace: kyverno
    values:
      kyverno:
        admissionController:
          initContainer:
            image:
              registry: registry.local/artifactory.algol60.net
              repository: csm-docker/stable/ghcr.io/kyverno/kyvernopre
          container:
            image:
              registry: registry.local/artifactory.algol60.net
        test:
          image:
            repository: registry.local/artifactory.algol60.net/csm-docker/stable/docker.io/library/busybox
        cleanupController:
          image:
            registry: registry.local/artifactory.algol60.net
        reportsController:
          image:
            registry: registry.local/artifactory.algol60.net
        backgroundController:
          image:
            registry: registry.local/artifactory.algol60.net
        cleanupJobs:
          admissionReports:
            image:
              registry: registry.local/artifactory.algol60.net
          clusterAdmissionReports:
            image:
              registry: registry.local/artifactory.algol60.net
        webhooksCleanup:
          image: registry.local/artifactory.algol60.net/csm-docker/stable/docker.io/bitnami/kubectl:1.26.4
        buildKyvernoTrust:
          image:
            registry: registry.local/artifactory.algol60.net
  - name: kyverno-policy
    source: csm-algol60
    version: 1.6.2
    namespace: kyverno
  - name: cray-kyverno-policies-upstream
    source: csm-algol60
    version: 1.0.0
    namespace: kyverno
