apiVersion: manifests/v1beta1
metadata:
  name: vshasta
spec:
  sources:
    charts:
    - name: csm-algol60
      type: repo
      location: https://artifactory.algol60.net/artifactory/csm-helm-charts/
  charts:
  - name: csm-redfish-interface-emulator
    source: csm-algol60
    version: 0.1.0
    namespace: services
