#!/bin/sh


TARGET_FILE=$1
YQ=$2

[ -z "$TARGET_FILE" ] && exit 1
[ -z "$YQ" ] && exit 1

cat <<EOF | $YQ w -i -s - $TARGET_FILE
- command: update
  path: spec.kubernetes.services.cray-nexus
  value:
    istio:
      ingress:
        hosts:
          ui:
            enabled: true
            authority: "{{ dns.uis.nexus }}"
EOF
