#!/bin/sh

TARGET_FILE=$1
YQ=$2

[ -z "$TARGET_FILE" ] && exit 1
[ -z "$YQ" ] && exit 1

cat <<EOF | $YQ w -i -s - $TARGET_FILE
- command: delete
  path: spec.kubernetes.services.cray-istio-deploy.istio.kiali.hub
- command: delete
  path: spec.kubernetes.services.cray-istio-deploy.istio.prometheus
- command: delete
  path: spec.kubernetes.services.cray-istio-deploy.istio.grafana
- command: delete
  path: spec.kubernetes.services.cray-istio-deploy.istio.tracing
EOF
