http://helmrepo.dev.cray.com:8080/:
  charts:
    cfs-hwsync-agent:
    - 1.4.4
    cfs-trust:
    - 1.1.6
    cms-ipxe:
    - 1.5.11
    cray-baremetal-etcd-backup:
    - 0.1.0
    cray-bos:
    - 1.7.15
    cray-ceph-csi-cephfs:
    - 3.1.3
    cray-ceph-csi-rbd:
    - 3.1.5
    cray-certmanager:
    - 0.5.0
    cray-certmanager-init:
    - 0.5.0
    cray-certmanager-issuers:
    - 0.4.0
    cray-cfs-api:
    - 1.6.14
    cray-cfs-batcher:
    - 1.4.8
    cray-cfs-operator:
    - 1.11.23
    cray-conman:
    - 1.4.7
    cray-crus:
    - 1.4.12
    cray-dhcp-kea:
    - 0.4.20
    cray-dns-powerdns:
    - 0.0.1
    cray-dns-unbound:
    - 0.2.16
    cray-drydock:
    - 2.7.0
    cray-etcd-backup:
    - 0.2.5
    cray-etcd-defrag:
    - 0.2.3
    cray-etcd-operator:
    - 0.15.1
    cray-externaldns:
    - 0.11.2
    cray-hms-bss:
    - 1.7.5
    cray-hms-capmc:
    - 1.23.5
    cray-hms-discovery:
    - 1.5.2
    cray-hms-firmware-action:
    - 1.7.7
    cray-hms-hbtd:
    - 1.10.4
    cray-hms-hmcollector:
    - 2.10.3
    cray-hms-hmnfd:
    - 1.7.3
    cray-hms-meds:
    - 1.14.6
    cray-hms-reds:
    - 1.18.4
    cray-hms-rts:
    - 1.11.3
    cray-hms-scsd:
    - 1.5.1
    cray-hms-sls:
    - 1.8.7
    cray-hms-smd:
    - 1.28.10
    cray-hms-trs-operator:
    - 1.4.2
    cray-ims:
    - 3.1.12
    cray-csm-barebones-recipe-install:
    - 1.1.4
    cray-istio:
    - 1.25.0
    cray-istio-deploy:
    - 1.19.0
    cray-istio-operator:
    - 1.19.0
    cray-kafka-operator:
    - 0.4.1
    cray-keycloak:
    - 1.11.2
    cray-keycloak-gatekeeper:
    - 0.3.2
    cray-keycloak-users-localize:
    - 1.6.0
    cray-metallb:
    - 0.12.3
    cray-metrics-server:
    - 0.1.2
    cray-nexus:
    - 0.6.0
    cray-node-discovery:
    - 0.5.3
    cray-node-labels:
    - 0.1.0
    cray-node-problem-detector:
    - 1.4.0
    cray-opa:
    - 0.13.5
    cray-postgres-operator:
    - 0.9.3
    cray-precache-images:
    - 0.2.0
    cray-product-catalog:
    - 0.2.0
    cray-s3:
    - 0.2.0
    cray-shared-kafka:
    - 0.4.1
    cray-sts:
    - 0.4.2
    cray-sysmgmt-health:
    - 0.8.8
    cray-tftp:
    - 1.4.7
    cray-tftp-pvc:
    - 1.3.6
    cray-uas-mgr:
    - 1.11.7
    cray-vault:
    - 1.0.5
    cray-vault-operator:
    - 1.0.1
    cray-velero:
    - 0.0.2
    csm-ssh-keys:
    - 1.1.3
    csm-config:
    - 1.5.5
    gitea:
    - 1.9.15
    sealed-secrets:
    - 0.1.0
    spire:
    - 0.8.13
    spire-intermediate:
    - 0.2.1
    trustedcerts-operator:
    - 0.1.1
