# NOT IN USE - use lofstman manifest files under ../manifests instead.
#
# Packaging index for Helm charts not listed in Loftsman manifests. Format is:
#
#   <repo>:
#     charts:
#       <name>:
#       - <version>
#       - ...
#
