http://helmrepo.dev.cray.com:8080/:
  charts:
    benji-k8s:
    - 0.5.0
    cfs-hwsync-agent:
    - 1.3.3
    cfs-trust:
    - 1.0.3
    cms-ipxe:
    - 1.4.4
    cray-baremetal-etcd-backup:
    - 0.1.0
    cray-bos:
    - 1.6.5
    cray-ceph-csi-cephfs:
    - 3.1.3
    cray-ceph-csi-rbd:
    - 3.1.5
    cray-certmanager:
    - 0.5.0
    cray-certmanager-init:
    - 0.5.0
    cray-certmanager-issuers:
    - 0.4.0
    cray-cfs-api:
    - 1.5.4
    cray-cfs-batcher:
    - 1.3.3
    cray-cfs-operator:
    - 1.9.4
    cray-conman:
    - 1.3.6
    cray-crus:
    - 1.3.5
    cray-dhcp-kea:
    - 0.4.4
    cray-dns-unbound:
    - 0.1.5
    cray-drydock:
    - 2.6.1
    cray-etcd-backup:
    - 0.2.2
    cray-etcd-defrag:
    - 0.2.2
    cray-etcd-operator:
    - 0.14.1
    cray-externaldns:
    - 0.11.2
    cray-hms-bss:
    - 1.5.4
    cray-hms-capmc:
    - 1.19.12
    cray-hms-discovery:
    - 1.2.8
    cray-hms-firmware-action:
    - 1.5.3
    cray-hms-hbtd:
    - 1.8.0
    cray-hms-hmcollector:
    - 2.8.8
    cray-hms-hmnfd:
    - 1.5.2
    cray-hms-meds:
    - 1.11.5
    cray-hms-reds:
    - 1.16.3
    cray-hms-rts:
    - 1.8.3
    cray-hms-scsd:
    - 1.3.3
    cray-hms-sls:
    - 1.5.6
    cray-hms-smd:
    - 1.26.8
    cray-hms-trs-operator:
    - 1.2.4
    cray-ims:
    - 3.0.4
    cray-csm-barebones-recipe-install:
    - 1.0.1
    cray-istio:
    - 1.24.0
    cray-istio-deploy:
    - 1.18.2
    cray-istio-operator:
    - 1.18.2
    cray-kafka-operator:
    - 0.4.1
    cray-keycloak:
    - 1.10.4
    cray-keycloak-gatekeeper:
    - 0.3.2
    cray-keycloak-users-localize:
    - 1.5.4
    cray-metallb:
    - 0.12.2
    cray-metrics-server:
    - 0.1.2
    cray-nexus:
    - 0.5.4
    cray-node-discovery:
    - 0.5.2
    cray-node-problem-detector:
    - 1.4.0
    cray-opa:
    - 0.13.2
    cray-postgres-operator:
    - 0.7.1
    cray-precache-images:
    - 0.2.0
    cray-product-catalog:
    - 0.0.2
    cray-s3:
    - 0.2.0
    cray-shared-kafka:
    - 0.4.1
    cray-sts:
    - 0.4.1
    cray-sysmgmt-health:
    - 0.6.0
    cray-tftp:
    - 1.3.3
    cray-tftp-pvc:
    - 1.2.3
    cray-tokens:
    - 0.3.0
    cray-uas-mgr:
    - 1.11.4
    cray-vault:
    - 1.0.2
    cray-vault-operator:
    - 1.0.1
    cray-velero:
    - 0.0.1
    csm-ssh-keys:
    - 1.0.3
    csm-config:
    - 1.1.1
    gitea:
    - 1.8.5
    sealed-secrets:
    - 0.1.0
    spire:
    - 0.8.2
    spire-intermediate:
    - 0.2.0
    trustedcerts-operator:
    - 0.1.1
