https://arti.dev.cray.com/artifactory/csm-helm-stable-local/:
  charts:
    cfs-hwsync-agent:
    - 1.3.8
    cfs-trust:
    - 1.0.8
    cms-ipxe:
    - 1.4.10
    cray-baremetal-etcd-backup:
    - 0.1.0
    cray-bos:
    - 1.6.22
    cray-ceph-csi-cephfs:
    - 3.1.3
    cray-ceph-csi-rbd:
    - 3.1.5
    cray-certmanager:
    - 0.5.0
    cray-certmanager-init:
    - 0.5.0
    cray-certmanager-issuers:
    - 0.4.0
    cray-cfs-api:
    - 1.5.12
    cray-cfs-batcher:
    - 1.3.8
    cray-cfs-operator:
    - 1.10.25
    cray-conman:
    - 1.3.13
    cray-crus:
    - 1.3.9
    cray-csm-barebones-recipe-install:
    - 1.0.6
    cray-dhcp-kea:
    - 0.4.22
    cray-dns-unbound:
    - 0.1.19
    cray-drydock:
    - 2.6.2
    cray-etcd-backup:
    - 0.2.5
    cray-etcd-defrag:
    - 0.2.3
    cray-etcd-operator:
    - 0.14.2
    cray-externaldns:
    - 0.11.2
    cray-hms-bss:
    - 1.5.8
    cray-hms-capmc:
    - 1.19.18
    cray-hms-discovery:
    - 1.2.10
    cray-hms-firmware-action:
    - 1.5.13
    cray-hms-hbtd:
    - 1.8.4
    cray-hms-hmcollector:
    - 2.8.10
    cray-hms-hmnfd:
    - 1.5.4
    cray-hms-meds:
    - 1.11.13
    cray-hms-reds:
    - 1.16.5
    cray-hms-rts:
    - 1.8.7
    cray-hms-scsd:
    - 1.3.3
    cray-hms-sls:
    - 1.5.13
    cray-hms-smd:
    - 1.26.20
    cray-hms-trs-operator:
    - 1.2.4
    cray-ims:
    - 3.0.13
    cray-istio:
    - 1.24.4
    cray-istio-deploy:
    - 1.18.9
    cray-istio-operator:
    - 1.18.3
    cray-kafka-operator:
    - 0.4.1
    cray-keycloak:
    - 1.10.7
    cray-keycloak-gatekeeper:
    - 0.3.2
    cray-keycloak-users-localize:
    - 1.5.6
    cray-metallb:
    - 0.12.3
    cray-metrics-server:
    - 0.1.2
    cray-nexus:
    - 0.6.0
    cray-node-discovery:
    - 0.5.3
    cray-node-labels:
    - 0.1.0
    cray-node-problem-detector:
    - 1.4.0
    cray-opa:
    - 0.13.6
    cray-postgres-operator:
    - 0.9.3
    cray-precache-images:
    - 0.2.0
    cray-product-catalog:
    - 0.0.5
    cray-psp:
    - 0.1.2
    cray-s3:
    - 0.2.0
    cray-shared-kafka:
    - 0.4.1
    cray-sts:
    - 0.4.2
    cray-sysmgmt-health:
    - 0.8.8
    cray-tftp:
    - 1.3.5
    cray-tftp-pvc:
    - 1.2.3
    cray-uas-mgr:
    - 1.11.7
    cray-vault:
    - 1.0.5
    cray-vault-operator:
    - 1.0.1
    cray-velero:
    - 0.0.2
    csm-config:
    - 1.1.5
    csm-ssh-keys:
    - 1.0.5
    gitea:
    - 1.8.12
    sealed-secrets:
    - 0.1.0
    spire:
    - 0.8.18
    spire-intermediate:
    - 0.2.2
    trustedcerts-operator:
    - 0.1.1
